### ISSUE TITLE
How to hide checked items

### ISSUE THREAD

**Issue by mustafaozhan** [kunesj/conkyKeep#9]
Hello as I mentioned in title is there any way to hide the items which are done and checked ?

**Comment by kunesj** [comment]
That's a good idea. Added: https://github.com/kunesj/conkyKeep/commit/be194eb61f5532fee6d49d3efe121a67e9965971

Just redownload conkyKeep and add this to your user config:
```
[Style]
NoteListHideChecked = yes
```

**Comment by mustafaozhan** [comment]
Hello, thank you so much for your update it works in the version you have i checked. But I am afraid that i am using old version of your conkyKeep and when i started to use I also deleted some functionalities like colors etc. My config file is still xml :smile: 

So if we can solve that issue from here 

```
            elif rn['type'] == "LIST": # if List note (root note type)
                for cn in childNotes:
                    if rn['formatedText'] != "":
                        rn['formatedText'] += "\n"

                    if cn['checked']:
                        rn['formatedText'] += "[X] "
                    else:
                        rn['formatedText'] += ""
                    rn['formatedText'] += cn['formatedText']
```

I would be double time thankful otherwise i need to use updated version and change back again all those staff.

I do not have so much python experience that's why i need your help 
```
                    if cn['checked']:
                        rn['formatedText'] += "[X] "
```
I just want to skip that row and not print it do you have any idea ?

those codes are from the version i have.

**Comment by kunesj** [comment]
You should use current version. 
The old version you are using has many bugs, some of them can make conkyKeep crash without explanation. The old version also does not support all note types (images) and sorts notes incorrectly.

>when i started to use I also deleted some functionalities like colors etc

You can disable different note colors by setting all colors in config the same. Unless you wanted transparent background, which I would need to implement.
```
[Style]
# Note colors; defaults are googleKeep colors; WHITE==DEFAULT==NONE
ColorRED = 255,138,128
ColorGREEN = 204,255,144
ColorBLUE = 128,216,255
ColorWHITE = 250,250,250
ColorORANGE = 255,209,128
ColorYELLOW = 255,255,141
ColorGRAY = 207,216,220
ColorTEAL = 167,255,235
```

**Comment by mustafaozhan** [comment]
Hello,

Actually as you mentioned, i need transparency. And i do not need the images also. If you check  [here](https://github.com/mustafaozhan/ArchGooglyConky) I make some stuff and part of it is including also your conkyKeep project inside. The bottom right side of screenshot is showing notes from Google Keep and the note Titled as To-do

**Comment by kunesj** [comment]
Looks like I already supported transparency without knowing. https://github.com/kunesj/conkyKeep/commit/7b610d64f4c9b8f73495b397719207850f7fcad5

Just set all alpha values to 0, like this:
```
[Style]
# Note colors R,G,B,A (0-255); defaults are googleKeep colors; WHITE==DEFAULT==NONE
ColorRED = 255,138,128,0
ColorGREEN = 204,255,144,0
ColorBLUE = 128,216,255,0
ColorWHITE = 250,250,250,0
ColorORANGE = 255,209,128,0
ColorYELLOW = 255,255,141,0
ColorGRAY = 207,216,220,0
ColorTEAL = 167,255,235,0
```

**Comment by mustafaozhan** [comment]
Okay i will give a try and than let you know beacuse it seems new version of conkyKeep needs much more dependency then previous one and i need to customize it again

**Comment by mustafaozhan** [comment]
```
elif rn['type'] == "LIST": # if List note (root note type)
                for cn in childNotes:
                    if rn['formatedText'] != "":
                    	if cn['checked']:
                    		pass
                    	else:
                    		rn['formatedText'] += "\n"
                        
                    if cn['checked']:
                        pass
                    else:
                        rn['formatedText'] += ""
                        rn['formatedText'] += cn['formatedText']
```

Seems that it supports what i want in old version for now. Even if it is not coded like a good pyhton programmer :smile:
